# modify from: https://github.com/isaacs/github/issues/415#issuecomment-561700485
name: Mirror Repo
on:
  schedule:
    # nightly (0th hour 0th minute of every day)
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Mirror
      run: |
        git config --global user.email "${{ secrets.EMAIL }}"
        git config --global user.name "XingerTang"
        git config pull.ff only
        git clone 'https://github.com/numpy/numpy.git'
        cd numpy/
        git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/XingerTang/numpy.git"
        git fetch github
        git pull github main
        git push github
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
